# -*- coding: utf-8 -*-
"""bigMartProblem.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1PnTYsMR8AMHqf630kg4gsCuWfwxmdEtd
"""

#import pandas library

import pandas as pd
import numpy as np

#reading csv file
df = pd.read_csv("data.csv")

#drop null value
df = df.dropna(how='any')

df = df.reset_index(drop=True)

df

#type covert
df.to_excel('data.xlsx')

#selecting the col by name
df['Item_Weight']

df[['Item_MRP', 'Item_Fat_Content']]

#Specific Row Selection
df[df['Item_Fat_Content'] == 'Regular']

#sort Values
#sort By Year
soterd_data = df.sort_values(by='Outlet_Establishment_Year')

soterd_data

soterd_data = df.sort_values(by='Outlet_Establishment_Year', ascending=False)
soterd_data

#Apply Function
df.apply(lambda x : x)

df.apply(lambda x:x[0])

#access col by index
df.apply(lambda x:x[0], axis=1)

#acess col by Name
df.apply(lambda x:x['Item_Fat_Content'], axis=1)

def clip_price(price):
  if price > 200:
    price = 200
  return price

df['Item_MRP']

df['Item_MRP'].apply(lambda x : clip_price(x))

#Aggregation
#groupby

#groupby for price
price_by_item = df.groupby('Item_Type')

#display first few rows
price_by_item.first()

price_by_item.Item_MRP.mean()

#multi col groupby
multiple_groups = df.groupby(['Item_Type', 'Item_Fat_Content'])
multiple_groups.first()

#crosstab distribution frequency
pd.crosstab(df['Outlet_Size'], df['Outlet_Location_Type'], margins=True)

pd.crosstab(df['Item_Fat_Content'], df['Item_MRP'], margins=True)

#pivot Table
pd.pivot_table(df, index=['Outlet_Establishment_Year'], values="Item_Outlet_Sales")

pd.pivot_table(df, index=['Outlet_Establishment_Year', 'Outlet_Location_Type', 'Outlet_Size'], values="Item_Outlet_Sales")

pd.pivot_table(df, index=['Outlet_Establishment_Year', 'Outlet_Location_Type', 'Outlet_Size'], values="Item_Outlet_Sales", aggfunc = [np.mean, np.median, min, max, np.std])