# -*- coding: utf-8 -*-
"""NumPy_YT.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1_lzEoFs0poPFzFU4Gd4ZPlOzUm7-0jRw
"""

import numpy as np

#1-D Array

a = np.array([1,2,3])
print(a)
a

type(a)

a.dtype

b = np.array([2.3, 4.5])
b

b.dtype

"""Multi-D Array"""

c = np.array([[1,2,3],[4,5,6]])
c

"""Initilaztion NumPy Array with Zero"""

n1 = np.zeros((1,2))
n1

n1 = np.zeros((10,10))
n1

"""Intilazing numpy with Same Number"""

n3 = np.full((3,3),(5))
n3

n4 = np.full((6,6), 23)
n4

"""Initilization NumPy array within a range"""

n5 = np.arange(1,51)
n5

n6 = np.arange(0,51,10)
n6

"""initilization numpy array random numbers"""

n7 = np.random.randint(1,101,10)
n7

"""Checking the shape of NumPy array"""

n8 = np.array([[1,2,3], [4,5,6]])
n8

n8.shape

n8.shape = (3,2)
n8

"""Joining Of NumPy Array"""

n9 = np.array([10,20,30])
n10 = np.array([40,50,60])

np.vstack((n9,n10))

np.hstack((n9,n10))

np.column_stack((n9,n10))

"""NumPy Intersection & Diffrence"""

n11 = np.array([10,20,30,40,50,60])
n12 = np.array([50,60,70,80,90])

np.intersect1d(n11,n12)

np.setdiff1d(n11,n12)

np.setdiff1d(n12,n11)

"""Mathematics of NumPy Array"""

n13 = np.array([10,20])
n14 = np.array([30,40])

np.sum([n13,n14])

np.sum([n13, n14], axis=0)

np.sum([n13,n14], axis=1)

n15 = np.array([10,20,30])

n15+1

n15-1

n15*5

n15/3

n16 = np.array([32,54,65,78,23,64,76,25,68,89,94,53])

np.mean(n16)

np.std(n16)

np.median(n16)

n17 = np.array([32,44,65])
n18 = np.array([45,76,22])

n17.dot(n18)

"""Save And Load NumPy"""

n19 = np.array([12,34,56,324,6743,76,5634,64,7534,564,35])
np.save('final_numpy_array', n19)

n20 = np.load('/content/final_numpy_array.npy')
n20