# -*- coding: utf-8 -*-
"""pandas_YT.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1zH6mfFPOz8cdGOGHATfUV-5994tGgiJ_
"""

import pandas as pd
import numpy as np

#Series 1-D Lable data
s1 = pd.Series([1,2,3,4,5])
s1

type(s1)

#change index
s2 = pd.Series([1,2,3,4,5], index=('a','b','c','d','e'))
s2

#Series Object From Dictionary
s3 = pd.Series({'a':100, 'b':200, 'c':300, 'd':400,'e':500})
s3

#change index in dictionary
s4 = pd.Series({'a':100, 'b':200, 'c':300, 'd':400,'e':500}, index=['d','c','a','e','b'])
s4

s5 = pd.Series([1,2,3,4,5,6,7,8,9])
s5

s5[4]

s5[:6]

s5[-5:]

s5[:-1]

s5[-1:]

#Basic Maths

s1+5

s6 = pd.Series([1,2,3,4,5])
s1+s6

"""Create DataFrame - Labled Multi-D data"""

df1 = pd.DataFrame({'Name':['Hitanshu','Shubham','Ansh','Ayush','Gaurav'], 'age':[21,21,20,20,21], 'TestScore_1':[80,82,85,90,95], 'TestScore_2':[85,86,88,93,98]})
df1

total_marks = df1['TestScore_1'] + df1['TestScore_2']
total_marks

#mean of test1
df1['TestScore_1'].mean()

#Comutative Sum
df1['TestScore_1'].cumsum()

df1['TestScore_1'].count()

df1['TestScore_1'].min()

df1['TestScore_1'].max()

#meadian
df1['TestScore_1'].median()

#variance 
df1['TestScore_1'].var()

df1['TestScore_1'].std()

#skewness
df1['TestScore_1'].skew()

df1['TestScore_1'].kurt()

df1.corr()

df1['TestScore_1'].describe()

"""Ploting(Boxplot) with Pandas"""

df1.boxplot(column='TestScore_1', by='TestScore_2')

iris = pd.read_csv('/content/iris.csv')
iris

iris.head()

iris.tail()

iris.shape

iris.describe()

iris.iloc[0:5,0:3]

iris.loc[5:10, ('Petal.Length', 'Species')]

"""Droping Col And Row

axis = 1 -> Col

axis = 0 -> Row
"""

iris.drop('Species', axis=1)

iris.drop([1,2,3], axis=0)

iris.mean()

iris.min()

iris.max()

iris.median()

#Apply
def double_make(s):
  return s*2

iris[['Sepal.Width', 'Petal.Width']].apply(double_make)

iris['Species'].value_counts()

iris.sort_values(by='Petal.Length')